version: '3.8'

services:
  service-backend:
    build:
      context: .
    container_name: blatant-api
    depends_on:
      -  service-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://blatant-postgres:5432/blatant
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - JWT_SECRET_ACCESS_KEY=${JWT_ACCESS_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
      - SPRING_JPA_SHOW-SQL=false
    expose:
      - "8080"
    ports:
      - "8080:8080"
    links:
      -  service-db

  service-db:
    image: postgres:15.1-alpine
    container_name:  blatant-postgres
    environment:
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
      - POSTGRES_DB=blatant
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: unless-stopped
    volumes:
      - service-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  service-pgAdmin:
    image: dpage/pgadmin4:latest
    container_name: blatant-pgAdmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - service-pgAdmin:/var/lib/pgadmin


volumes:
  service-db:
  service-pgAdmin: